# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(736, 434)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 711, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.date = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.date.setObjectName("date")
        self.gridLayout.addWidget(self.date, 6, 1, 1, 2)
        self.kilometers = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.kilometers.setMaximumSize(QtCore.QSize(200, 16777215))
        self.kilometers.setObjectName("kilometers")
        self.gridLayout.addWidget(self.kilometers, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.toyota = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.toyota.setObjectName("toyota")
        self.gridLayout.addWidget(self.toyota, 1, 0, 1, 1)
        self.service_check = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.service_check.setObjectName("service_check")
        self.gridLayout.addWidget(self.service_check, 4, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.service_climate = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.service_climate.setObjectName("service_climate")
        self.gridLayout.addWidget(self.service_climate, 5, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.volvo = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.volvo.setObjectName("volvo")
        self.gridLayout.addWidget(self.volvo, 1, 2, 1, 1)
        self.peugeot = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.peugeot.setObjectName("peugeot")
        self.gridLayout.addWidget(self.peugeot, 1, 1, 1, 1)
        self.service_oil = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.service_oil.setObjectName("service_oil")
        self.gridLayout.addWidget(self.service_oil, 3, 0, 1, 3)
        self.logo = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.logo.setMinimumSize(QtCore.QSize(300, 0))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 1, 3, 6, 1)
        self.reserve = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.reserve.setObjectName("reserve")
        self.gridLayout.addWidget(self.reserve, 7, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Serwis Samochodowy"))
        self.toyota.setText(_translate("Dialog", "Toyota"))
        self.service_check.setText(_translate("Dialog", "Przegląd 200zł"))
        self.label_3.setText(_translate("Dialog", "Przebieg:"))
        self.service_climate.setText(_translate("Dialog", "Serwis Klimatyczny 150zł"))
        self.label_4.setText(_translate("Dialog", "Data:"))
        self.volvo.setText(_translate("Dialog", "Volvo"))
        self.peugeot.setText(_translate("Dialog", "Peugeot"))
        self.service_oil.setText(_translate("Dialog", "Serwis Olejowy 300zł"))
        self.reserve.setText(_translate("Dialog", "Zarezerwój"))
